### ISSUE TITLE
Systemd unit need both Requires and After for nm-unmetered-connection to work

### ISSUE THREAD

**Issue by andrewcchen** [erikw/restic-automatic-backup-scheduler#100]
Need to add `After=nm-unmetered-connection.service` after the Requires line

https://github.com/erikw/restic-automatic-backup-scheduler/blob/9e60df6caa0c76084cf1d9f3663451c32e9e46b3/usr/lib/systemd/system/restic-backup%40.service#L6

Reference: https://stackoverflow.com/a/62805159

**Comment by erikw** [comment]
Thank you @andrewcchen ! I've updated accordingly:)
