### ISSUE TITLE
Run backup as restic user

### ISSUE THREAD

**Issue by ilyanep** [erikw/restic-automatic-backup-scheduler#104]
Hello!

Following the example in the restic docs, I've set up restic to run as a separate user (rather than root). I believe I'll want to make use of the systemd timer implementation in this repo, but I'm not familiar enough with systemd timers to know for sure if my planned solution sounds like it'd work. 

I think what I want to do is instead of installing the timer and service into `/usr/lib/systemd/system` like the Makefile does by default, I'll want to put it into `~restic/.config/systemd/user/` and enable lingering sessions for my restic user.

Does that sound about right? If I get this figured out, would it be valuable for me to contribute an option to make install that way back to this repo?

Thank you for putting this together! This is bound to really help me out with setting up my new backup system.

**Comment by erikw** [comment]
Hey, fun that you explore different ways of running it. The best solution is (well can be) the tailored one

The aim of this project is not to cover all ways of doing it, as it makes it too complicated. But a summary of your findings would be nice to have documented here if someone is interested in a similar setup that you're doing :)

**Comment by ilyanep** [comment]
Finally got around to doing this...

Not sure how I missed it but it turns out you can still put the service unit in the system directory and specify `User=restic` and `Group=restic` under the `[Service]` header and it just works:

```
[Unit]
Description=Run Restic backup

[Service]
Type=simple
ExecStart=/home/restic/restic-backup.sh 2>&1 | systemd-cat
WorkingDirectory=/home/restic
User=restic
Group=restic
```
