### ISSUE TITLE
Mac OS LaunchAgent

### ISSUE THREAD

**Issue by trumblejoe** [erikw/restic-automatic-backup-scheduler#105]
brew services start restic-automatic-backup-scheduler

Afai can tell this LaunchAgent doesn't do anything. I've tried working through the manual steps and it won't start either. The launchctl status is 1 which I believe rates back to permissions error. I have double checked my launched shell script can run through terminal. I'm running on user permissions but root on the LaunchAgent didnt seem to change anything either. Is it maybe related to the $PATH variables in the LaunchAgent? I'm not 100% sure but I thought translating path variables in a launchagent wasn't supported?

Brew Service List didn't list a file associated with the service so that may be another issue.

**Comment by erikw** [comment]
Hello,

I don't have access to my Mac system where I have this installed. Meanwhile:

* https://www.launchd.info/ is a really good resource on launchd and debugging
* If you think there's an issue expanding $PATH, try manually replacement it with the fully expanded path and to rule out if this is the issue

How did you install the Launch Agent from this README? Did you double check to follow all steps? :)

**Comment by trumblejoe** [comment]
My suspicions were correct, it was a path issue in the LaunchAgent.

Modifying $INSTALL_PREFIX isn't part of the Brew install instructions, it's **only** listed in the manual setup. Replacing $INSTALL_PREFIX with $(brew --prefix) was sufficient to correct the issue. The replacement needed to be applied to PATH, and to each command being sent through the programarguments.

Running as a user still isn't getting me around mac System Integrity Protection but I've atleast made progress to getting this LaunchAgent to run successfully.
