### ISSUE TITLE
How to allow user unmount?

### ISSUE THREAD

**Issue by Fnordbert** [erikw/restic-automatic-backup-scheduler#108]
Hi and thanks for simplifying the use of restic for backup!

To make it even more practical for family members I want to create a small "script button" or .desktop file that will allow mounting the backup under /media/$USER/restic/ so that it appears in Nautilus. (using --allow-other)
This works fine using pkexec to run the script as root to be able to source the default.env etc.
This however, leaves the user unable to unmount the "drive" in Nautilus the expected way.
I would like to avoid having a separate script with pkexec to unmount if at all possible, but I have tried a number of approaches without luck. 
Any ideas are appreciated!

**Comment by erikw** [comment]
Hey, this sounds like a great setup that you're making.

Unfortunately I don't have an Ubuntu system at the moment to help figuring this out. But I'll leave the issue open here for others to drop in :).
