### ISSUE TITLE
Revise non-optional settings

### ISSUE THREAD

**Issue by nettnikl** [erikw/restic-automatic-backup-scheduler#109]
Hi!

Currently i'm experimenting with this project and identified an issue.

I'd like to ask you to rethink on the assertions of environment variables.
`assert_envvars` checks for values I'd like not to set. Most prominently, i set up a password command, so setting "`RESTIC_PASSWORD_FILE`" stops a successful execution.
I also removed: `B2_ACCOUNT_ID B2_ACCOUNT_KEY B2_CONNECTIONS RESTIC_PASSWORD_FILE`

I see some options, me preferring the options on top of the list:
1. Remove the checks for all not-strictly needed settings (what i did locally as a workaround)
2. Convert them into a warning
3. Check whether one of `RESTIC_PASSWORD_FILE` or `RESTIC_PASSWORD_CMD` is set
4. Document a workaround

This affects
https://github.com/erikw/restic-automatic-backup-scheduler/blob/085d72274768702e34fcaf42558d451fa72cf16b/bin/restic_check.sh#L28 and https://github.com/erikw/restic-automatic-backup-scheduler/blob/085d72274768702e34fcaf42558d451fa72cf16b/bin/restic_backup.sh#L36.

**Comment by erikw** [comment]
Hi,

the idea was to detect early on that the configuration is not proper, as from experience it was cryptic to understand the error messages that comes from trying to use unset environment variables later in the script. This is why the assertions are done.

Option 3 or 2 would be best I'd say. PR is welcome :)
