### ISSUE TITLE
Allow space in extra args

### ISSUE THREAD

**Issue by nettnikl** [erikw/restic-automatic-backup-scheduler#111]
Hi!

It seems, `IFS=' ' read -ra extra_args <<< "$RESTIC_BACKUP_EXTRA_ARGS"` does not respect escaped spaces.

If you print out the entries in `"${extra_args[@]}"` you can see that they are split:
```
--option
sftp.command='ssh\
-F\
/etc/restic/ssh_config\
restic-backup-host\
-s\
sftp'
--exclude-caches
--one-file-system
```
In this example, it leads to -F (option for sftp) to be used as option for restic.

Not sure how to resolve - use `RESTIC_BACKUP_EXTRA_ARGS` somehow like an array? Or allow escapes?

**Comment by nettnikl** [comment]
For reference: this is the relevant part of the config env:
```bash
export RESTIC_BACKUP_EXTRA_ARGS="--option sftp.command='ssh\ -F\ /etc/restic/ssh_config\ restic-backup-host\ -s\ sftp'"
export RESTIC_BACKUP_EXTRA_ARGS="$RESTIC_BACKUP_EXTRA_ARGS --exclude-caches"
export RESTIC_BACKUP_EXTRA_ARGS="$RESTIC_BACKUP_EXTRA_ARGS --one-file-system"
```

**Comment by nettnikl** [comment]
In https://stackoverflow.com/a/27297061/7343513 there is the following said:
> ... uses the <<< operator, which only takes a single word, so read gets a single whitespace-separated string and splits it into a list of-separated, so that an argument containing whitespace is split into multiple array elements.

Which is exactly what happens here.
```bash
$ cmdArgs=( "$@" )
$ printf "%s\n" "${cmdArgs[@]}"
foo bar
baz
```
is suggested. What do you think?

**Comment by erikw** [comment]
@nettnikl could you please try this PR https://github.com/erikw/restic-automatic-backup-scheduler/pull/112 and see if that works for you?

```bash
$ cd restic-automatic-backup-scheduler
$ git fetch
$ git switch allow-escaped-spaces
```

**Comment by nettnikl** [comment]
I'm getting `subprocess ssh: ssh: Could not resolve hostname restic-backup-host: Name or service not known` , however this seems to be caused by restic unlock not getting this arg.

Commenting this out, i'm getting `unknown flag: --option sftp.command`.

Btw:
The command produced looks fine, and works when executed manually:
`restic backup --verbose=3 --one-file-system --tag systemd.timer --option b2.connections=5 --exclude-file /path/exclude --option sftp.command=ssh\ -F\ /etc/restic/ssh_config\ restic-backup-host\ -s\ sftp --exclude-caches --one-file-system .`
