### ISSUE TITLE
Improve resilience of systemd-backup task

### ISSUE THREAD

**Issue by strowi** [erikw/restic-automatic-backup-scheduler#117]
Hi,

thx for this neat project, i've been using restic on our k8s-servers for a while already, but with this i've now come around again to try it on the linux-desktops.;)

I've noticed a small problem with the `restic-backup@default.service` - when resuming from suspend or similar that service (at least sometimes) is too fast and fails because the network is not up yet. Even adding sth. like 

```bash
After=network.target network-online.target
Wants=network-online.target
```

didn't work.  Still throwing 

```bash
Jun 11 09:28:19 sleipnir systemd[1]: Started Backup with restic to Backblaze B2.
Jun 11 09:28:35 sleipnir cat[276324]: Fatal: unable to open config file: Stat: Head "https://s3.xyz/a/b/c": dial tcp: lookup s3.xyz on 127.0.1.1:53: server misbehaving
```

Yes, this is S3, but that shouldn't matter to the DNS-resolution not working. After adding a small `while !ping google.de; do sleep...` to the service the error is gone.

**Comment by erikw** [comment]
I'm afraid I can't help you to debug this further. But please share here if you find something out.

You don't seem to be alone with issues using `After=network.target...`, and the suggestion solution could be to create a system "ping target", see:

https://unix.stackexchange.com/a/538901

**Comment by strowi** [comment]
I couldn't find any related issue, so i just wanted to leave that here. 

It seems to be a mix between network (which is up in my case) and the local DNS resolver (systemd-resolved) being able to resolve queries. 
I'll try adding that as a dependency, but don't think that will work either (systemd-resolved is a bit of a pita). So i will keep the `until ping..` solution.

Thx!
