### ISSUE TITLE
Install fails on windows, pwsh not found

### ISSUE THREAD

**Issue by ScottyDoesKnow** [erikw/restic-automatic-backup-scheduler#124]
I got the same error as in issue #116 installing on Windows 10. PowerShell was obviously installed, but I installed it through scoop as well and no luck. Also tried running as admin and no luck. Got it to install by just calling the install script through powershell.

When I did install it through powershell, I got this output, but it seemed to work fine anyway:

```
TaskPath                                       TaskName                          State
--------                                       --------                          -----
\                                              restic_backup                     Ready
Could not find app path for 'git'.
\                                              restic_check                      Ready
```

**Comment by erikw** [comment]
Can you run a minimal push script like the one I posted here?

https://github.com/erikw/restic-automatic-backup-scheduler/issues/116#issuecomment-1588070630

**Comment by ScottyDoesKnow** [comment]
Same thing. I had uninstalled pwsh since it didn't do anything so I installed it again, opened a new git bash window but same result:

```
$ pwshtest.sh
bash: pwshtest.sh: command not found
```

**Comment by erikw** [comment]
OK then the issue is scoped down to being able to run powershell in a shebang shell script.
https://stackoverflow.com/questions/48216173/how-can-i-use-a-shebang-in-a-powershell-script/48218913#48218913

I can't provide further support on this as I don't have access to a Windows installation at the moment. But please report back if you find the solution :)

**Comment by ScottyDoesKnow** [comment]
Alright, so in my defense, my only linux experience is a bit of messing around with a Raspberry Pi haha. So apparently there's a difference between running `pwshtest.sh` and `./pwshtest.sh`. Changing that gave me this output:

```
$ ./pwshtest.sh
/usr/bin/env: ‘pwsh’: No such file or directory
```

And then installing pwsh through scoop gave me this output:

```
$ ./pwshtest.sh
Processing -File './pwshtest.sh' failed because the file does not have a '.ps1' extension. Specify a valid PowerShell script file name, and then try again.
```

So issue #116 was caused by not installing pwsh through scoop, adding that to step 2 in the Windows section should fix everything.

**Comment by erikw** [comment]
Aha! There we go. Thanks for debugging. I updated the README
https://github.com/erikw/restic-automatic-backup-scheduler/commit/1c0ba09d7051cb3398210f85e4d183fb4dedf815

**Comment by ScottyDoesKnow** [comment]
Of course. Thanks for the ridiculously quick help!
