### ISSUE TITLE
Rename repo to `restic-automatic-backup-scheduler`

### ISSUE THREAD

**Issue by erikw** [erikw/restic-automatic-backup-scheduler#67]
After #51 & #52 it would appropriate to rename this repo from `restic-systemd-automatic-backup` to

* ~~simply `restic-automatic-backup`~~
* ~~or `restic-automatic-backup-systemd-cron-launchagent-scheduledtasks` for discoverability~~
* `restic-automatic-backup-scheduler`

- [x] Rename repo
- [x] Rename internal repo references
- [x] Update external links to repo
- [x] Rename brew Formula & test
- [x] Verify Windows works
- [ ] Rename AUR PKGBUILD test
   - [x] Publish new AUR https://aur.archlinux.org/packages/restic-automatic-backup-scheduler
   - [x] Test
   - [ ] Get old package stats merged in to new https://lists.archlinux.org/pipermail/aur-requests/2022-February/067144.html

**Comment by gerardbosch** [comment]
:clap:  :clap:  very nice! I've been secretly thinking on that for some weeks :joy: 

I arrived to this project from your comment here in 2018: https://github.com/restic/restic/issues/519#issuecomment-380339995 Keep in mind to update that link there if you rename the repo :upside_down_face: 

`restic-automatic-backup` sounds cool! Maybe `scheduler` could also fit?

I find the second too long :laughing:  -for discoverability there should probably be other mechanisms.

**Comment by erikw** [comment]
`restic-automatic-backup-scheduler` could work 👍 

Haha look at that. I see we even had a small conversation there

In my experience, GitHub will redirect old repo to new URL. But I'll make sure to update that comment just to make sure it works ;)

**Comment by gerardbosch** [comment]
Github is very clever :) I didn't think on automatic redirects, hehe. Cool!
