### ISSUE TITLE
Provide optional desktop notifications with backup stats

### ISSUE THREAD

**Issue by gerardbosch** [erikw/restic-automatic-backup-scheduler#77]
Hi! As you know, I've been using very happily this project for some years :tada: to backup my personal laptop.

But there is something that I have always find missing: Have a little feedback about the daily backup, and how my repository was growing.

This is mainly for 2-3 reasons:
- To see if I added by mistake any directory that is not intended to be backed up, and be able to notice that and react fast to (a) add it to `~/.backup_exclude.txt`; and (b) remove that heavy-sized snapshot from the repository to save money :)
- Have non-intrusive notice that the backup is working, as if for example I realize that the notification didn't popped up in the last days, I need to troubleshoot something.
- To see if my backup snapshot is growing more than I'd like.

But instead of digging daily in logs to see what happened the last day, I would like to see a small notification on my desktop. So with that in mind I wrote something to accomplish it the easiest way I could think of :) I put it as a draft PR https://github.com/erikw/restic-systemd-automatic-backup/pull/76, to see what you think, here is a sample of the result :)

![image](https://user-images.githubusercontent.com/30733556/153260757-fe48bdcf-a780-452a-b983-9110334c6ce5.png)

**Comment by gerardbosch** [comment]
As with this approach the notification is on the user-side it should work on any platform :) including root systemd in Linux.

Also I've found some cross-platform notification apps in Python or Node.js, that could enable a universal notification if the notification trigger was added to this project. I started with `notify-send` (libnotify) on Linux, but lately I'm switching to something more general to send notifications: https://github.com/gerardbosch/dotfiles/blob/main/_shallow-symlinks/bin/keyboard-triggers/notify-desktop

**Comment by erikw** [comment]
Resolved by #76
