### ISSUE TITLE
Can't find both restic-backup.service and status-email-user.service

### ISSUE THREAD

**Issue by AgingOrange** [erikw/restic-automatic-backup-scheduler#88]
> Now edit restic-backup.service and status-email-user.service to call this service failure.

I can't seem to find these files. I do have:
- /usr/lib/systemd/system/restic-backup@.service
- /etc/systemd/system/status-email-user@.service

I did _Setup Linux Systemd_ and then _Optional: Email Notification on Failure_. Did I miss a step?

**Comment by erikw** [comment]
These are the correct files you have. The documentation needs to be updated. I think that quoted text was written before the services got support for multiple profiles.

I'll update the documentation soon!
