### ISSUE TITLE
resticw error

### ISSUE THREAD

**Issue by AgingOrange** [erikw/restic-automatic-backup-scheduler#89]
On running `resticw snapshots` I get the following error: 

./resticw: line 129: INSTALL_PREFIX: unbound variable

This is on Ubuntu 20.04 installed with `sudo make install-systemd`.

**Comment by erikw** [comment]
No worries. It was a bad idea to have the scripts checked in to the repo with execution permission, when they actually can't be executed until after the Makefile has processed them. I removed the execution bits now in the repo :)
