### ISSUE TITLE
Unable to source in current shell `sudo: source: command not found`

### ISSUE THREAD

**Issue by VictorioBerra** [erikw/restic-automatic-backup-scheduler#94]
```bash
pi@mypi:~$ source /etc/restic/default.env.sh
-bash: /etc/restic/default.env.sh: Permission denied
pi@mypi:~$ sudo source /etc/restic/default.env.sh
sudo: source: command not found
pi@mypi:~$
```

`Linux mypi 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux`

```
pi@mypi:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

**Comment by VictorioBerra** [comment]
More info:

```
pi@mypi:~$ ls -lah /etc/restic/
total 24K
drwxr-xr-x  2 root root 4.0K May 11 12:56 .
drwxr-xr-x 94 root root 4.0K May 11 11:56 ..
-rw-------  1 root root  139 May 11 11:56 backup_exclude.txt
-rw-------  1 root root 2.1K May 11 12:31 default.env.sh
-rw-------  1 root root 1.7K May 11 12:49 _global.env.sh
-rw-------  1 root root   29 May 11 11:56 pw.txt
```

This is immediately after running:

`$ git clone https://github.com/erikw/restic-automatic-backup-scheduler.git && cd $(basename "$_" .git)`

and

`sudo make install-systemd`

**Comment by erikw** [comment]
Hm I would be interested to know what shell is being invoked by your sudo. Not all shells support the `source` command. This project was written with bash in mind, but is known to will with zsh as well. Plain `sh` would use the command `.` instead of `source`.

**Comment by VictorioBerra** [comment]
@erikw 

```
pi@mypi:~$ echo "$SHELL"
/bin/bash
pi@mypi:~$ source
-bash: source: filename argument required
source: usage: source filename [arguments]
pi@mypi:~$ .
-bash: .: filename argument required
.: usage: . filename [arguments]
```

**Comment by erikw** [comment]
Ok looks good. Does it work to enter sn interactive shell and then source? I.e.

```console
$ sudo -s # or sudo -i
# source /etc/restic/default.env.sh
```

**Comment by VictorioBerra** [comment]
@erikw Yeah it dopes but then im root and commands like rclone fail because it cant find /home/root/.config/rclone etc.

I need to make another issue but my backups aren't running and theres no output at all in journalctl. This is sort of an X-Y problem I suppose since I cant even source to the current shell and test by running `/bin/restic_backup.sh`

**Comment by VictorioBerra** [comment]
```
pi@mypi:~/BirdNET-Pi$ sudo -s
root@mypi:/home/pi/BirdNET-Pi# source /etc/restic/default.env.sh
root@mypi:/home/pi/BirdNET-Pi# /bin/restic_backup.sh
B2_ACCOUNT_ID must be set for this script to work.

Did you forget to source a /etc/restic/*.env.sh profile in the current shell before executing this script?
root@mypi:/home/pi/BirdNET-Pi#
```

```
root@mypi:/home/pi/BirdNET-Pi# cat /etc/restic/_global.env.sh

# The restic repository encryption key
export RESTIC_PASSWORD_FILE="/etc/restic/pw.txt"
# The global restic exclude file
export RESTIC_BACKUP_EXCLUDE_FILE="/etc/restic/backup_exclude.txt"

export RESTIC_VERBOSITY_LEVEL=1
export RESTIC_NOTIFY_BACKUP_STATS=false
```

```
# shellcheck source=etc/restic/_global.env.sh
. "/etc/restic/_global.env.sh"

export RESTIC_REPOSITORY="rclone:remote:/data1/home/de1913/birdnetpi"   # *EDIT* fill with your repo name

# What to backup. Colon-separated paths e.g. to different mountpoints "/home:/mnt/usb_disk".
# To backup only your home directory, set "/home/your-user"
export RESTIC_BACKUP_PATHS="BirdNET-Pi/scripts/birds.db:BirdSongs/Extracted/By_Date/"

# A tag to identify backup snapshots.
export RESTIC_BACKUP_TAG=systemd.timer

# Retention policy - How many backups to keep.
export RESTIC_RETENTION_DAYS=14
export RESTIC_RETENTION_WEEKS=16
export RESTIC_RETENTION_MONTHS=18
export RESTIC_RETENTION_YEARS=3
```

**Comment by erikw** [comment]
This is the key:

```
root@mypi:/home/pi/BirdNET-Pi# /bin/restic_backup.sh
B2_ACCOUNT_ID must be set for this script to work.
```

The problem is exactly as the message says. This script is written with usibg B2 in mind. I see your storage backed is rclone. See here the default profile:
https://github.com/erikw/restic-automatic-backup-scheduler/blob/main/etc/restic/_global.env.sh#L19


To use rclone, you would need to modify the solution just slightly.

If you ate lucky, you would just need to remove rhe B2 envvars from here:
https://github.com/erikw/restic-automatic-backup-scheduler/blob/main/bin/restic_backup.sh#L36

YMMV I've not used the rclone storage backend myself:)

**Comment by VictorioBerra** [comment]
Okay that helped, simply gutting the `B2_*` stuff from  `/bin/restic_backup.sh` allowed me to run `/bin/restic_backup.sh` manually and see a successful backup. For rclone, I needed to add the following env vars:

```
export RCLONE_CONFIG_REMOTENAME_TYPE=sftp
export RCLONE_CONFIG_REMOTENAME_HOST=myuser.rsync.net
export RCLONE_CONFIG_REMOTENAME_USER=myuser
export RCLONE_CONFIG_REMOTENAME_PORT=22
export RCLONE_CONFIG_REMOTENAME_KEY_FILE=/home/pi/.ssh/myuser_rsync_id_rsa
```

This is because rclone will not be able to find its config when run as root. I suppose I could also move/link the config in roots/.config folder too.

@erikw to test the timer, how can I manually trigger the systemd timer?

**Comment by VictorioBerra** [comment]
`sudo systemctl start restic-backup@default.service` worked! Ill check tomorrow and see if it went off at midnight as expected.
