### ISSUE TITLE
line 77: extra_args[@]: unbound variable

### ISSUE THREAD

**Issue by dikkatdeli** [erikw/restic-automatic-backup-scheduler#96]
hello,

I use this script for wasabi. I changed B2_ACCOUNT_ID B2_ACCOUNT_KEY line to :  AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY

I get this error:

/bin/restic_backup.sh: line 77: extra_args[@]: unbound variable

Can you help ?

**Comment by dikkatdeli** [comment]
Also: 

systemd gives error :  Executable path is not absolute, ignoring: bash -c 'set -o pipefail; ps cax

I added:  ExecStart=**/bin**/bash -c 

it fixed

**Comment by erikw** [comment]
Hello,

In not at my computer right now, but I Susie to that you need to modify this line in the restic backup script that asserts that all needed variables are set:

https://github.com/erikw/restic-automatic-backup-scheduler/blob/main/bin/restic_backup.sh#L37

**Comment by dikkatdeli** [comment]
> Hello,
> 
> In not at my computer right now, but I suspect that you need to modify this line in the restic backup script that asserts that all needed variables are set:
> 
> https://github.com/erikw/restic-automatic-backup-scheduler/blob/main/bin/restic_backup.sh#L37

yes, I changed that but it gives an error. IDK why.

**Comment by erikw** [comment]
It's the `-u` at 
https://github.com/erikw/restic-automatic-backup-scheduler/blob/main/bin/restic_backup.sh#L12
that causes "unbound variable", meaning that a variable is being referenced that has not been defined. 

It complains at the command starting at line 77 
https://github.com/erikw/restic-automatic-backup-scheduler/blob/49cc054eebf12f7aec6d61c5c4cd8c94aef7c90b/bin/restic_backup.sh#L77

May I guess that it could be maybe that `$B2_CONNECTIONS` is not set? As you are not using B2, this line should be removed.

**Comment by dikkatdeli** [comment]
> It's the `-u` at
> 
> https://github.com/erikw/restic-automatic-backup-scheduler/blob/49cc054eebf12f7aec6d61c5c4cd8c94aef7c90b/bin/restic_backup.sh#L12
> 
> 
> that causes "unbound variable", meaning that a variable is being referenced that has not been defined.
> It complains at the command starting at line 77
> 
> https://github.com/erikw/restic-automatic-backup-scheduler/blob/49cc054eebf12f7aec6d61c5c4cd8c94aef7c90b/bin/restic_backup.sh#L77
> 
> May I guess that it could be maybe that `$B2_CONNECTIONS` is not set? As you are not using B2, this line should be removed.

Even If I remove the line:   "--option b2.connections="$B2_CONNECTIONS" \  " 
B2_CONNECTIONS is set 10 so it is not empty.
still gives the error. 

Also, systemd was not working without the full path of I added: ExecStart=**/bin/**bash -c

**Comment by erikw** [comment]
> Even If I remove the line: "--option b2.connections="$B2_CONNECTIONS" \ "
> B2_CONNECTIONS is set 10 so it is not empty.
> still gives the error.

All right, we have learned this one was not the problem. There are quite a few variables used in this line. You can figure out which one it is that is not set by e.g. adding `set -x` at the top of the script, which is the same as running it like

```console
$ source /etc/restic/default.env.sh
$ bash -x /path/to/restic_backup.sh
```
and inspect the debug output.

Or you can simply inject some `echo` prints in the script just before the failing line :)





> lso, systemd was not working without the full path of I added: ExecStart=**/bin/**bash -c

Interesting. May I ask what Linux dist you are using and the version? I have been using Arch Linux only with this project and for this dist, it works as it currently looks.
