### ISSUE TITLE
Run a backup on demand? Storage backends other than Backblaze?

### ISSUE THREAD

**Issue by JohnMaguire** [erikw/restic-automatic-backup-scheduler#99]
Hi there -

Thanks for this software, it's great! I'm using it on my NAS with great success.

I'm currently setting it up on my macOS laptop and I was wondering about two things:

1. Is it possible to run a backup on-demand? I frequently download new photos from my camera to my laptop and would like to immediately trigger a backup. I tried `resticw backup` and get the output below.
2. Is it possible to specify a storage backend other than Backblaze? Ideally I'd have my macOS laptop backing up to both my NAS (via SFTP or rest-server) and to Backblaze. I'm happy to configure this as two separate profiles, but AFAICT the code is actively asserting that Backblaze-specific environment variables are set and passes B2-specific options to restic.

```
❯ resticw backup
‣ Using profile: default  --  (/opt/homebrew/etc/restic/default.env.sh)

Fatal: nothing to backup, please specify target files/dirs
```

**Comment by erikw** [comment]
Heh @JohnMaguire!



> 1. Is it possible to run a backup on-demand? I frequently download new photos from my camera to my laptop and would like to immediately trigger a backup. I tried `resticw backup` and get the output below.

Yes that's possible. The current `resticw` is a simple wrapper and is not directly supporting backup out of the box with no args. The best way forward with how this project currently looks is:
```bash
 $ source $(brew --prefix)/etc/restic/default.env.sh
 $ $(brew --prefix)/usr/bin/restic_backup.sh # something like this, don't have time to check exact path right now
```





> 2\. Is it possible to specify a storage backend other than Backblaze? Ideally I'd have my macOS laptop backing up to both my NAS (via SFTP or rest-server) and to Backblaze. I'm happy to configure this as two separate profiles, but AFAICT the code is actively asserting that Backblaze-specific environment variables are set and passes B2-specific options to restic.

That's correct. Currently this project is for B2 only. I should add this to the README to clarify under https://github.com/erikw/restic-automatic-backup-scheduler#project-scope. The intention of this repo is to be a starting point for users to customize their own perfect backup solution. A solution that tries to solve all problems is out of scope here :). But maybe that changes ...

Thus, should should be able to use a different provider for sure. You would need to set the provider specific options in the profile and maybe a few adjustments in `restic_backup.sh` as well.

**Comment by JohnMaguire** [comment]
@erikw Thanks a lot! This is very helpful. A README clarification would be great (it currently mentions that Backblaze is recommended.) The project scope makes sense, and I'm happy tweaking the script for my own needs - I just wanted to make sure this was the best path forward. Thanks again for the code - cheers!

**Comment by JohnMaguire** [comment]
Just for sake of posterity, here's the command I ran to run a backup immediately:

```
source $(brew --prefix)/etc/restic/default.env.sh && caffeinate -i /opt/homebrew/bin/restic_backup.sh
```

The `caffeinate -i` part prevents idle sleep during the backup.
